// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package intel_power_gadget

import (
	"github.com/elastic/beats/v7/libbeat/asset"
)

func init() {
	if err := asset.SetFields("metricbeat", "intel_power_gadget", asset.ModuleFieldsPri, AssetIntelPowerGadget); err != nil {
		panic(err)
	}
}

// AssetIntelPowerGadget returns asset data.
// This is the base64 encoded gzipped contents of module/intel_power_gadget.
func AssetIntelPowerGadget() string {
	return "eJzsms1u4zYQgO9+isGeEqAJ0B59KBA0wKKH7Qbd9GzQ0lhRIokqSSVxn76QLNmyRIqUNJSbIjm1tpb8Zjz81XcDL7hfQ5wpTDY5f0OxiVgYoVoBqFgluIYv/S+/rAAEJsgkrmGLiq0AQpSBiHMV82wNv64AQNMqpDwsElwB7GJMQrmunruBjKW4hiAvqv8HUPsc1xAJXuT1J5rmzxtpN5Sz4IVFePy8abAEilC0Ptc2e/j7o0i3KIDv4PcyDsgFD1BKLprmgWegnmIJci8Vpj0KydI86UPw7TMGyo3B0LM0dd1PyVlaXqLbuoVNxs8eMWfIQjgrUya4gAuUPvh+e/gLqsYPRAgyxyDexRhqauacLWabLZO42Qn8u8As2Gv5Ql5sExyHV0KVTcOx6Q5d0MDdap79CVgiOQjcoRAYguLAZPWvWfiKQsUSw/bT8eHLlL3HaZFCxrMbVYgtr5o+Pnc7lIeUvXtKQ0PlmIn+453ofq5+bTgE6BBcpDwFdxgYVfUKpjCEr6OitY4YFeZkrA/1oH18QpGyBO5RxlEGDzzOFFw93j9cmziNmGVSFaY5CqYK0eWZjvqtzuBzkQXlM9DqZHwyI7VhryxO2FZPuOU8QZbN/OUjwfKnOJBw9fXxuizYus+kS+w2KWGGItp7AG/mSjj0AHnCMpzJGwqW+iO+//PuGyVtnjC148Ij8UPdAxW1ilOUiqX5RiomlH6cMTVylN3VWxmoGj11YkHALKQGwCy0dF8ONPHKEm3PCc+iiT2HhWDlQ/pO2WnJuE37VTB9gruDsrnTWDwtFSwQXEpgSVLvaHZcdCqltwE1EcekwHFWzcmemdk7JXO9jnhl3lT/IdVSFVJ3hyFs9xXx92ppjLMIflT7cLj6/uPaS4BLFdQFQ1yq/pYKsTqm374xpfQnr6lb+qpd2KJ6QzwsZb/0mOQw1DMvus/MparX24lYrV2m38Hc3s7O/oXPqP2OUH/cfocdKXeh4iT+p79rmFu7rXb7kJaK1h9+IrXUkfc0r43KZhuwmYKXAnWcgMfG46M6tJG0y2UUZHO34GNlaO4Ypq8O53TES0SDN2OZOB4evaSvOTfOyN85H3UCOwfbKYTVZYGP7FX3BNMz1+Iizlr7AmPOmPBx1dYMifYSOWo6obyiHLiaHLtKl8umZfXLqul/4u2Z6XIXw/p7F179e512JJptqCXFDkHAaUv6ypKi38Kx9952kqzzemtp6b+3LSTrv94i9vs31tDgBoWolhw3JZ8lN6XzD1Nytnl+VrGZX6V81tH/rI5sZ5GesuDA0D2p6kvIdZfTV0RAq4mUf10zxQFY6780f4NKheZlzOVdCu0wnP5TjrdQTGkDVxvFlkUH6tnZNMHq7BRy3pGmSpfVZqsAyRzz3zdXNHkZEjzo0nIJk6UbrMVmoQmW0mzpBmC2W2jYiUyXLvaw7UKDPt986VKb7RewSA6OyOQmTDcCqw1DFAiVGdPld7BjiCKgMGW69I62DFEEVOYMONszMCSwOFI7mTR6pL5NQwpkNmvAbtfAkGEzlkRr2sAI2wYoD49kRog5Au8H0AVi8H6I9R7DkJ1DFswlTB17wJcowAuHfIl6XTJk82szmkCnmT1aSO07NDrKCa/TYJTtQ4NKb/4MRbHciPcbx3LDmDwO850rTQy0phC42UI06BTmkAnY8HJuEXBKkwhcbSKPkY02i2CUXURDPt00MtN6XLJmmEcwzj4i4p1uIg3w+kzwDDMJ3O0kGtiJppKB02NWp5pLMMpeomGdbDLBoM1EAzfXbIIRdhMMiwKOxNSmEwy8OwS7NgD2n8ExMLApBGDVCMhhBpUCsGoF5DxGxQAmGFLgqx6XsKXgs2zNMB+6bF3WI5KCJTOu4LMWzTAfuhZdznlaxceRidbaWv0bAAD//2uDXkM="
}
